#!/usr/bin/env ruby

require 'bundler/setup'
require 'optparse'
require 'yaml'

project_base      = File.expand_path(File.join(__dir__, '..'))
default_data_file = File.join(project_base, 'data', 'main-sets.yml')
lib_dir           = File.join(project_base, 'lib')

$:.unshift(lib_dir)
require 'simple_thread_exercise'

OptionParser.new do |o|
  o.banner = "Usage: #$0 [options] DATA_FILE ..."
  o.on('-v', '--version', 'Print version and exit') do
    puts SimpleThreadExercise::VERSION
    exit(0)
  end

  o.parse!
end

if ARGV.empty?
  ARGV.unshift(default_data_file)
end

project_sets = [YAML.load(ARGF.read)].flatten.compact
project_sets.each do |data|
  project_set = SimpleThreadExercise::Models::ProjectSet.new(data)
  name        = project_set.name
  cost        = project_set.total_cost
  puts("%s Cost: $%0.2f" % [ name, cost ])
end
